# Generated by Django 5.1.7 on 2025-03-13 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pirvate_question_pirvate_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirvate_choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pirvate_question'),
        ),
    ]
